### ISSUE TITLE
Bootstrap de backend - 3h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#1]
## Objetivo
O objetivo aqui é criar o projeto base, sem nenhum recurso ou configuração adicional, mas já deixar pronta a API para as próximas tarefas.

- Não precisa incluir o husky ainda
- Não comitar dados reais no .env nem em outros arquivos

## Tarefas
- [x] Criar projeto API
- [x] Usar base padrão de projeto Adonis
- [x] Adicionar linter
- [x] Adicionar prettier
- [x] Incluir comando de checks no package, para validar linter, prettier, yarn
- [x] Explicar no readme como rodar o projeto e alguma informação extra relevante

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/07/21 - 04/07/21
Work session total: 1:53:26
Billable: No

Grand total: 1:53:26
