### ISSUE TITLE
Obter dados da cidade para o portal - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#10]
## Objetivo
O objetivo é criar um endpoint que retorne todos os dados para o portal, que serão utilizados pra construir o front. 
Este endpoint será chamado no next internamente para o SSR, e talvez de tempos em tempos para atualizar a interface.

## Tarefas
- [x] Criar endpoint público que recebe o id da cidade
- [x] Retornar `prefecture`, `places`, `agenda` (de hoje só)

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/07/21 - 04/08/21
Work session total: 0:56:48
Billable: No

Grand total: 0:56:48
