### ISSUE TITLE
Onde vacinar - 4h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#108]
## Objetivos
O usuário poderá ver os pontos de vacinação mais próximos, bastando para isso dar a permissão de localização, então a lista será atualizada por distância (backend) para o utilizador se decidir melhor.

## Ver por distância
- [x] Pensar em como dizer ao usuário que tem como ver por distância. Talvez por agora um botão "Pontos mais próximos" que iria desencadear todo o processo. Dai depois validamos visualmente onde encaixar isso.

## Pedir permissão
- No carers, ele não me pede a permissão "normalmente", ele já diz que está bloqueado e preciso ir nas opções da página autorizar. Pensar como ajustar neste caso aqui.
- [x] Explicar que é preciso dar a permissão de localização
- [x] Pedir permissão para localização
- [x] Se não der, deixar uma mensagem, com uma forma de dar a permissão novamente
- [x] Pedir a permissão logo que a pessoa entrar? Vamos pensar nisso.

## Obter lista de places
- [x] Assim que tiver as coordenadas, salvar em um estado local e solicitar a API a lista dos places informando as coordenadas (alinhar com Bruno parametros)
- [x] Exibir para cada place a distância em metros/kilometros

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/19/21 - 04/20/21
Work session total: 4:00:37
Billable: No

Grand total: 4:00:37
