### ISSUE TITLE
Criar frontend do portal - 4h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#12]
## Objetivo
O objetivo é criar o front do portal com base no design já criado.

- Os dados serão obtidos do backend em uma próxima issue

## Tarefas
- [x] Criar interface da home do portal, como se fosse de uma única cidade mesmo (Juiz de Fora)
- [x] Colocar dados mock só pra gente ver alguma informação
- [x] Ajustar interface para o responsivo

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/07/21 - 04/08/21
Work session total: 4:35:45
Billable: No

Grand total: 4:35:45
