### ISSUE TITLE
Cidadão informar fila - 7h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#126]
## Objetivo
O objetivo aqui é permitir ao cidadão informar a fila, bastando para isso estar perto do local de vacinação.

## Back
- [x] Endpoint que recebe um post de informação de fila, contendo o prefectureId, placeId, e o status da fila
- [x] Se atributo `prefecture.enablePublicQueueUpdate===fase` não aceitar a requisição na prefeitura em questão
- [x] Calcular uma média da fila informada nos últimos 20 minutos, e setar este valor
- [x] Inserir `queueStatus` com `ip` do cara

## Front
- [x] Se `prefecture.enablePublicQueueUpdate===fase`, não exibir a opção de informar fila, nem antes nem depois de ter a localização
### Informar, sem ter localização confirmada
- [x] Ter um botão "Informar fila" ao lado da localização, que só estará visível se a pessoa não tiver compartilhado a localização ainda
- [x] Pedir permissão de localização, quando obter o dado, se a pessoa não estiver perto de nenhum ponto falar "Você precisa estar próximo de um dos pontos de vacinação para informar a fila."
### Informar, com localização
- Próximo - type fixed - 200 metros ou menos
- Próximo - type driveThru - 1km ou menos
- [x] Se a pessoa estiver próximo do ponto de vacinação, aparecer um botão "Informar fila" no place
- [x] Ao clicar abrir popup tipo do admin, com opções
- [x] Enviar post para backend (validar com Bruno url)
- [x] Depois de informar, salvar hora, se for informar novamente em menos de 2 minutos falar "É preciso aguardar pelo ao menos dois minutos para informar novamente o tamanho da fila"

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/20/21 - 04/20/21
Work session total: 2:19:37
Billable: No

Grand total: 5:07:17

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/20/21 - 04/22/21
Work session total: 2:47:40
Billable: No

Grand total: 5:07:17
