### ISSUE TITLE
Ajustes de publicação - 6h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#132]
## Backend
- [x] Conferir minutos pra aceitar o post no place do mesmo ip, direto no controller
- [x] Se place não tiver CEP, ou não conseguir obter a coordenada, tentar obter coordenadas a partir da URL do map (se tiver), buscando pela string, (ou até pela API mesmo?)
- [x] SMS sent false https://rollbar.com/AppMasters/Mapa-da-Vacina/items/412/ - Qual pode ter sido o motivo? Logar também o resultado do envio.
- [x] Ao receber um status de fila na cloudfunction (com `ip` ao invés de `userId`), se tiver uma atualização de um usuário autenticado nos últimos 20 minutos, não trocar o `queueStatus`, ou seja, manter do usuário autenticado por 20 minutos

## Portal
- [x] Tornar lista um grid, pra ocupar melhor a tela (👁 mandar print no canal)

## Front
- [x] Quando cidadão for informar o status a primeira vez no place, exibir "A ferramenta irá comparar sua informação com as de outros usuários, para determinar qual o tamanho será informado."
- [x] Pesquisar se tem como abrir link do Google Maps já no modo "rota"

## Admin
- [x] Tirar nome do usuário do centro, e colocar na sidebar mesmo, pode ser bem pequeno, numa section entre a logo e as opções. Se comprimir o menu pode sumir com o nome. (👁 mandar print no canal)
- [x] Separar submenus e deixar ser dois itens do menu (places)
- [x] Em usuários, la grid está "Convidar Usuários", deveria ser "Usuários convidados"
- [x] "Cargo" trocar por "Função" em todo lugar no admin
- [x] Para cada usuário (convidado e aceite) ter tb os botões de whatsapp e telefone (👁 mandar print no canal)

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/22/21 - 04/22/21
Work session total: 4:17:19
Billable: No

Grand total: 8:13:54

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/22/21 - 04/22/21
Work session total: 3:56:35
Billable: No

Grand total: 8:13:54
