### ISSUE TITLE
Criar mockups - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#139]
## Objetivos
Precisamos de uns mockups para divulgar o projeto, naquela ideia de celular na frente e foto embaçada atrás.
Já temos um bocado de prints na [pasta do drive](https://drive.google.com/drive/folders/1irA_NCKn4zlvEp-hulws7fay2XBrw7ag). Pode cortar e ajustar como precisar.

## Tarefas
- [x] Criar uns três mockups com filas e mãos segurando celulares. Enviar no canal pra gente validar.

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/26/21 - 04/26/21
Work session total: 1:14:26
Billable: No

Grand total: 1:14:26
