### ISSUE TITLE
Obter dados de uma prefeitura - 3h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#14]
## Objetivo
O objetivo é realmente montar a interface com os dados da API.

## Tarefas
- [x] Deixar o id de um prefeitura hardcoded (ver com o Bruno)
- [x] Obter da API os dados e construir a visualização
- [x] Comentar no canal quais dados faltam para irmos adequando
- [x] Verificar como poderia ser obtido o dado da API, no máximo uma vez a cada minuto (independente do numero de usuários)
- [x] Verificar como obter dados atualizados a cada minuto (do mesmo endpoint) pra atualizar a interface

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/08/21 - 04/08/21
Work session total: 2:11:43
Billable: No

Grand total: 2:11:43
