### ISSUE TITLE
Obter url do Google Maps - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#143]
O objetivo é facilitar preencher a url do maps, e consequentemente as coordenadas do local

## Tarefas
- [x] Criar command, que recebe uma cidade, e irá buscar as URLS do Google Maps dos locais
- [x] Obter locais na cidade sem Google Maps, chamar a API do Google passando o nome do local, cidade e estado
- [x] Se o retorno for bem certo de ser o que queremos, salvar a URL no `place` (isso irá fazer a function obter a coordenada certa)
- [ ] Talvez, talvez, dê pra comprar as coordenadas obtidas do local, comparar com a do CEP, pra ter certeza que os dois são perto mesmo (pra confirmar que achamos o lugar certo)

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/30/21 - 04/30/21
Work session total: 1:41:29
Billable: No

Grand total: 1:41:29
