### ISSUE TITLE
Bug fixes - 4h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#148]
Estão rolando alguns bugs online, dai precisamos ajustar por aqui.

## Backend
- [x] Abriu lugares que não deveriam abrir naquele dia. Conferir o código que seta o `openToday`, pra garantir que abrirá hoje corretamente.
- [x] Onde abre/fecha os lugares, juntar todos os places num objeto, e mandar só um log pro Rollbar

## Front
- [x] O front não tá obtendo dados novos a cada X segundos, deveria estar
- [x] Não logar no rollbar quando [falhar no fetch](https://rollbar.com/AppMasters/Mapa-da-Vacina/items/8/?item_page=0&item_count=100&#instances), pq pode floodar nosso rollbar
- [x] Conferir o warning ["Only request geolocation information in response to a user gesture."](https://stackoverflow.com/questions/47581575/only-request-geolocation-information-in-response-to-a-user-gesture), pensar qual seria a melhor forma de obter sem ser ao carregar.. se faz sentido isso ou não.

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 05/04/21 - 05/04/21
Work session total: 1:38:37
Billable: No

Grand total: 4:20:04

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 05/03/21 - 05/04/21
Work session total: 2:41:27
Billable: No

Grand total: 4:20:04
