### ISSUE TITLE
Filtros e ordenações no front - 3h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#149]
O objetivo é permitir ao usuário filtrar para ver só o que tem aberto, bem como ordenar de duas maneiras.

## Tarefas
- [x] Adicionar botões de filtro para "Aberto" / "Fechado"
- [x] Permitir ordenar por distância, e por ordem alfabética (ordem padrão)

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 05/03/21 - 05/04/21
Work session total: 1:33:44
Billable: No

Grand total: 1:33:44
