### ISSUE TITLE
Ajustes no admin - 4h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#150]
## Tarefas
- [x] Menus de movimentação primeiro, deixar nesta ordem: Dashboard, Atualização, Pontos de Vacinação, Usuários
- [x] Pra quem vê vários pontos (tanto no menu "pontos" quando em "atualização", ter input de busca parcial (mandar print no canal)
- [x] Refazer exibição dos pontos (menu "atualização"), pra grid. Dai no desktop ao invés de linhas, podem ter N colunas, e a orientação de cada item ficará mais vertical  (mandar print no canal)
- [x] Na lista de places (menu "pontos"), se um place não tiver google maps, ou não tiver coordenadas, ficar vermelha clara a linha, pra chamar atenção pra isso (mandar print no canal)

**Comment by lcastrof** [comment]
via Hubstaff
User: Lucas de Castro Fernandino

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 05/03/21 - 05/04/21
Work session total: 7:00:44
Billable: No

Grand total: 7:00:44
