### ISSUE TITLE
Configuração por dia da semana - 10h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#151]
A ideia é criar uma view nova no admin só ligada aos dias da semana, horários, status de aberto/fechado, para facilitar gerir esta informação.

## Backend
- [x] Propor uma estrutura dos dados
- [x] Ter `open` por dia da semana
- [x] Ter horário de abrir e fechar por dia da semana
- [x] Manter o `openToday` e `openTomorrow`, mas, pensar como será quando o usuário editar algo e mudar no admin, definindo que abre ou não hoje ou amanhã (com base nos dias da semana)

## Admin
- [x] Ter um botão na grid para editar só para os dias e horários, pode ser "Agenda" ou "Horários", pode ter ícone de calendário ou relógio
- [x] Apresentar os dias da semana (segunda, terça...), se abre ou não, e dois inputs de horário que abre e fecha
- [x] Remover os inputs "abre hoje", "abre amanhã" do popup (pode manter na grid), mover o input "aberto agora" pra o popup de horário novo

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 05/03/21 - 05/06/21
Work session total: 3:38:42
Billable: No

Grand total: 14:09:18

**Comment by lcastrof** [comment]
via Hubstaff
User: Lucas de Castro Fernandino

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 05/04/21 - 05/07/21
Work session total: 10:30:36
Billable: No

Grand total: 14:09:18
