### ISSUE TITLE
Fixes e ajustes

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#155]
- [x] Quando marca em ver as distâncias, ele continua ordenado por nome.. deveria, ao ser clicado neste botão e obtida a coordenada, alternar pra exibição por distância.
- [x] Mesmo estando próximo ao local, não está exibindo a opção de informar a fila. Conferir o bug e me falar o que era. Aumentar mais uns 100 metros pra pessoa poder informar.
- [x] Mandar video destes dois itens funcionando por favor no canal antes de abrir PR

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 08/16/21 - 08/16/21
Work session total: 0:30:49
Billable: No

Grand total: 0:30:49
