### ISSUE TITLE
Abrir hoje, abrir amanhã, na agenda

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#159]
## Descrever o bug
Ao editar um place e informar que abriria no dia de hoje (dia da semana), ou amanhã, ao salvar, na grid não ficou marcado "Abre hoje" e "abre amanhã".

## Issues relacionadas
- Issue #157 

## Como reproduzir
Passos para acontecer o bug:
1. Vá até os pontos de vacinação
2. Clique em "editar" da agenda de um ponto
3. Marque que abrirá no dia de hoje e de amanhã
4. Salve e veja que na grid não fica "Abre hoje" e "abre amanhã" marcado

## Comportamento esperado
Que "Abre hoje" e "abre amanhã" ficassem marcados.

**Comment by lcastrof** [comment]
via Hubstaff
User: Lucas de Castro Fernandino

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 05/10/21 - 05/10/21
Work session total: 0:32:43
Billable: No

Grand total: 0:32:43
