### ISSUE TITLE
Incluir AWS SDK - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#16]
## Objetivo
Para enviarmos SMSs (e emails também no futuro) precisamos incluir o SDK da Amazon.

## Tarefas
- [x] Importar pacote
- [x] Criar Provider 
- [x] Criar .env e config para configurações dos serviços, com as chaves necessárias
- [x] Criar método que recebe o telefone e mensagem
- [x] Enviar SMS e retornar sucesso ou falha

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/08/21 - 04/08/21
Work session total: 1:55:01
Billable: No

Grand total: 1:55:01
