### ISSUE TITLE
Convidar usuários - 3h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#17]
## Objetivo
A ideia aqui é ter uma rota para incluir usuários na coleção de users, como convidados.

## Convidar usuários
O usuário administrador, pode convidar usuários de todas as roles. Ele deverá dizer a prefeitura, e poderá dizer o place, para vincular a pessoa no lugar certo.
- [x] Criar rota POST `/invite` que receberá `{ phone, name, role, prefectureId, placeId }`
- [x] Validar e santizar telefone
- [x] Deixar nome com "Maiuculas e Minusculas" certinho antes de salvar (pegar do carers)
- [x] Adicionar ao convite, o usuário que convidou
- [x] Incluir na coleção de users da prefeitura

## Roles e dados
- [x] Se a role do convidado for `prefectureAdmin` deve ser informado apenas `prefectureId`
- [x] Se a role do convidado for `placeAdmin` ou `queueObserver` deve ser informado `prefectureId` e `placeId`
- [x] Se a role do convidado for `superAdmin`, não precisa de nada mais

## Quem pode convidar
- [x]  `superAdmin` pode convidar outro `prefectureAdmin`
- [x] `prefectureAdmin` pode convidar `prefectureAdmin`, `placeAdmin` e `queueObserver`
- [x] `placeAdmin` pode convidar `queueObserver`

## Enviar convite
- [x] Após validação, enviar SMS para telefone com "Você foi convidado para {function} - Comece agora acessando {URL_FRONT_ADMIN}"
- [x] Valores de function por role 
```
superAdmin - administrar o sistema filômetro
prefectureAdmin - administrar a prefeitura de {city} no filômetro
placeAdmin - administrar "{place title}" no filômetro
queueObserver - atualizar a situação da fila no sistema
```

## SuperAdmin
- [x] Criar colection `admins` "na raiz"
- [x] Ter telefone, name, active
- Ele não será convidado, iremos incluir "na mão via banco"

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/08/21 - 04/09/21
Work session total: 3:01:35
Billable: No

Grand total: 3:01:35
