### ISSUE TITLE
Confirmar usuário - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#18]
## Objetivo
A ideia aqui é confirmar que o usuário que acabou de se registrar ou autenticar no front, é um usuário válido pra nós, se foi convidado.

## Tarefas
- [x] Criar rota POST `/validate-user` que receberá o user do firebase
- [x] Adicionar `uid` na tabela de `user`

## Recebendo uma requisição
- [x] Receber `{uid, phone}`
- [x] Sanitizar telefone
- [x] Procurar se existe algum `user` com o `uid` informado (que já autenticou alguma vez), se existir, "retornar sucesso"
- [x] Conferir se o usuário foi convidado (em todas as prefeteituras), buscando `user` sem data de aceite, sem `uid`, e com o telefone informado
- [x] Se foi convidado e nunca logou, marcar como convite aceito salvando no registro do `user` o id do user do auth, data do aceite, e demais informações relevantes, setar active true, retornar o "retorno de sucesso"
- [x] Conferir se `phone` é de algum usuário `admin`, se for retornar sucesso
- [x] Se não foi convidado (e não é admin), retornar 401 "Seu telefone não está na lista de convites para utilizar o filômetro, fale com o responsável pelo ponto de vacinação ou da prefeitura"

## Retorno de sucesso
- [x] Se for `user`, retornar um objeto `user`, com role, `prefecutre` e `place` caso tenha
- [x] Se for `admin`,  retornar o objeto `admin`

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/09/21 - 04/09/21
Work session total: 2:03:02
Billable: No

Grand total: 2:03:02
