### ISSUE TITLE
Autenticar no admin - 5h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#19]
## Objetivo
A ideia aqui é permitir ao usuário entrar no admin, se ele tiver sido convidado.

## Autenticar
- [x] Criar interface de autenticação, usando o Phone do Firebase auth
- [x] Ao autenticar com sucesso, confirmar se é usuário convidado via API, enviando o numero de telefone e o id usuário
- [x] Se API confirmar usuário, ir para dashboard

## Confirmar usuário e salvar objeto `user` ou `admin`
- [x] Enviar post para API  (ver rota com Bruno) enviando o usuário do auth, e o número do telefone.
- [x] A API irá verificar se é um usuário válido, convidado e tal. Se não for irá retornar 401 com uma mensage, pode exibir ela para o usuário
- [x] Se for válido, a API irá retornar um objeto `admin`, ou um objeto `user` com `place` e `prefecture` opcinais. Salvar todo esse retorno no localStorage, para conferir quando precisar (irá precisar).

## Autenticado?
- [x] Criar método que verifica se usuário está autenticado, antes de renderizar qualquer cosia. Pode exibir um loading enquanto verifica.
- [x] Esperar firebase dizer se está logado, e conferir no localStorage a confirmação da API, só com os dois, seguir em frente
- [x] Quando autenticar, se não tem no localStorage a confirmação, chamar API pedindo confirmação, e então salvar algo no localStorage
- [x] Se autenticado e confirmado, levar pra dashboard
- [x] Se autenticado e não confirmado, mostrar o erro que vem da API
- [x] Se não autenticado, levar para rota de login

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/08/21 - 04/12/21
Work session total: 6:36:42
Billable: No

Grand total: 6:36:42
