### ISSUE TITLE
Bootstrap de frontend - 5h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#2]
## Objetivos
O objetivo é criar os projetos de front. Um será o "admin", que será usado tanto para o admin, quanto para o ponto de vacinação em si indicar o tamanho da fila. O outro será o "portal" que será por onde o usuário verá os pontos de vacinação e a indicação da quantidade de fila.

- Não comitar dados reais no .env nem em outros arquivos

## Admin
- [x] Criar projeto admin
- [x] Criar estrutura de pastas igual ao Carers
- [x] Incluir ant design no projeto
- Não importar todas as ferramentas por agora
- [x] Ter apenas uma view "Filômetro admin" no render
- [x] Adicionar linter
- [x] Adicionar prettier
- [x] Incluir comando de checks no package, para validar linter, prettier, yarn
- [x] Explicar no readme como rodar o projeto e alguma informação extra relevante

## Portal
- [x] Criar projeto portal
- [x] Criar estrutura de pastas igual ao Carers
- [x] Incluir ant design no projeto
- Não importar todas as ferramentas por agora
- [x] Ter apenas uma view "Filômetro portal" no render
- [x] Adicionar linter
- [x] Adicionar prettier
- [x] Incluir comando de checks no package, para validar linter, prettier, yarn
- [x] Explicar no readme como rodar o projeto e alguma informação extra relevante

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/07/21 - 04/07/21
Work session total: 2:13:22
Billable: No

Grand total: 2:13:22
