### ISSUE TITLE
CRUD de Usuários e convites - 7h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#23]
## Objetivo
O objetivo é listar os usuários. Alguns usuários poderão convidar outros usuários, e esta interface será para visualizar os usuários, convites já enviados, e enviar novos convites.

- O front irá comunicar diretamente com o firestore, sem passar pelo backend
- Os convites, são na verdade, os usuário

## Menu
- [x] Se o usuário não for da role `queueObserver`, ele poderá ver usuários e enviar convites, então exibir o menu
- [x] Adicionar menu "Usuários"

## Listar usuários
- [x] Abrir interface listando os usuários (users com convite aceito, active true) com as seguintes colunas: nome, role, prefecture e place
- [x] Só exibir `prefecture` se o usuário autenticado for da role `superAdmin` 
- [x] Botão de ação "Desativar" - ao clicar pedir confirmação "Deseja mesmo desativar este usuário?" - então trocar o `active` do usuário no firestore

## Listar convites
- [x] Incluir section "Convites enviados"
- [x] Listar os convites enviados com as seguintes colunas: nome, role, prefecture e place, convite (invitedAd)
- [x] Só exibir `prefecture` se o usuário autenticado for da role `superAdmin` 

## Convidar
- [x] Incluir um botão "Convidar" perto da lista de convites
- [x] Ao clicar, exibir formulário para convite
- [x] Informar sempre: telefone, nome, role
- [x] Informar de acordo com regras abaixo: lista de prefeituras
- [x] Informar de acordo com regras, ao escolher uma prefeitura: lista de places
- [x] Enviar post pra API (ver rota com Bruno), se receber erro, exibir. Se der sucesso, é sucesso. :)

### Regras de role
- As roles são:
```
superAdmin
prefectureAdmin
placeAdmin
queueObserver
```
- [x] Se o usuário autenticado for da role `superAdmin`, pode convidar qualquer role
- [x] Se o usuário autenticado for da role `prefectureAdmin`, pode convidar `prefectureAdmin`, `placeAdmin`, `queueObserver`
- [x] Se o usuário autenticado for da role `placeAdmin`, pode convidar apenas `queueObserver`

### Regras de convite
Ao selecionar a role do usuário a ser convidado...
- [x] Não terá como convidar um `superAdmin` (ele será incluído via banco, sempre)
- [x] Se a role selecionada for `prefectureAdmin`, se o usuário autenticado for `superAdmin`, exibir o select de prefeituras - é obrigatório selecionar uma
- [x] Se a role selecionada for `prefectureAdmin`, se o usuário autenticado não for `superAdmin`, a prefeitura deverá ser a mesma do usuário autenticado
- [x] Se a role selecionada for `placeAdmin`, se o usuário autenticado for `superAdmin`, deverá exibir a lista de prefeituras e locais (em branco) - deverá escolher uma prefeitura, para listar os locais - é obrigatório selecionar os dois selects
- [x] Se a role selecionada for `placeAdmin`, se o usuário autenticado não for `superAdmin`, deverá exibir a lista e locais apenas, já com todos os locais daquela cidade - é obrigatório selecionar o local e enviar também a prefeitura

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/09/21 - 04/12/21
Work session total: 7:10:56
Billable: No

Grand total: 7:10:56
