### ISSUE TITLE
Cloud functions e rules - 4h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#26]
- [x] Sempre que um novo `queueUpdate` for incluído, levar o status dele para o `place`
- [x]  Sempre que um novo `queueUpdate` for incluído, levar o `open` dele para o `place`

## Rules
- [x] Só permitir usuário com role `placeAdmin` alterar dados dentro da prefeitura dele

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/09/21 - 04/15/21
Work session total: 5:05:29
Billable: No

Grand total: 5:05:29
