### ISSUE TITLE
Enviar atualização da fila - 5h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#27]
## Objetivo
Permitir aos usuários `queueObserver` e `placeAdmin` enviarem atualizações sobre a fila, bem como informar se o local está aberto ou fechado.

- Vamos discutir como fazer isso antes de começar, pra gente ficar bem alinhado.

## Tarefas
- [x] Se o usuário for da role `queueObserver`, o dashboard dele será esta view
- [x] Se o usuário for da role `placeAdmin`,  terá um menu "Atualizar"

## Componente `<queueStatusUpdate/>`
Este componente será a única coisa no dashboad do `queueObserver`, e será exibido diversas vezes para o `placeAdmin` numa lista.
- Os dados importantes que este componente precisa mostrar, e mudar quando quiser são: status da fila, se o local está aberto ou fechado.
- [x] Receber dia props a `prefecture` e `place`

### Fechado
Se estado `open!=true`...
- [x] Ter apenas botão "Abrir ponto de vacinação", mais nada. Ao clicar confirmar "Deseja realmente abrir este ponto de vacinação agora?". Ao confifrmar adicionar via firestore um `queueUpdates`, com `open=true` e `status=noQeue` do`place` recebido via props.
### Aberto
Se estado `open==true`...
- [x] Exibir o estado da fila atual em destaque
- [x] Ter botão "Atualizar fila", onde escolherá algum dos estados (podendo ser o mesmo) e confirma. Criar novo registro de `queueUpdates` via firestore, com `open=true` e o `status`  recebido do usuário, no`place` recebido via props.
- [x] Ter um elemento visual mostrando "Ultima atualização incluída há {x minutos}"
- [x] Se passar de 15 minutos, deixar esse elemento vermelho, com destaque, pra indicar que ele precisa atualizar novamente
- [x] Ter botão no final do componente "Fechar ponto de vacinação". Ao clicar confirmar "Deseja realmente fechar este ponto de vacinação agora?". Ao confifrmar mudar via firestore `open=false` e `status=null`  do`place` recebido via props.

## Dashboard do `queueObserver` e do `placeAdmin`
- [x] Trará apenas o componente de status, da prefeitura/place que ele observa

## Menu "Atualizar" para o `prefectureAdmin` e  `superAdmin`
O admin poderá atualizar status de todos os places da prefeitura.. então iremos listar os places da prefeitura, e exibir o componete de status em cada um deles
- [x] Listar todos os places, cada place em um "card", e dentro do card ter o componente de informar o status
- [x] Se o usuário autenticado for `prefectureAdmin`, listar todos os places da `prefecture` dele
- [x] Se o usuário for `admin`, listar todas as `prefectures`, e dentro delas os places

## Menu "Atualizar" para o  `superAdmin`
- [x] Obter todas as prefeituras, fazer uma section para cada, e dentro de cada uma ter o loops dos places

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/13/21 - 04/13/21
Work session total: 5:38:29
Billable: No

Grand total: 5:38:29
