### ISSUE TITLE
Validar tudo junto - 8h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#29]
Conferir como tudo funciona junto.

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/12/21 - 04/12/21
Work session total: 1:35:47
Billable: No

Grand total: 2:38:52

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/12/21 - 04/12/21
Work session total: 1:03:05
Billable: No

Grand total: 2:38:52
