### ISSUE TITLE
Super admin

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#31]
## Objetivo
Realizar ajustes na interação do super admin

## Usuários
- [x] Menu terá "Usuários"
- [x] Obter todas as prefeituras, para cada uma ter uma section com o componente dos usuários dentro
- [ ] Ficar ligado, que quando incluir um convite terá que lidar com a prefeitura do loop (via prop), então é fixo de ser um usuário daquela prefeitura
- [x] O admin da prefeitura, só pode incluir gente na própria prefeitura
- [x] Quando o select tiver uma opção só, (prefeitura), já vir selecionada

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/13/21 - 04/13/21
Work session total: 2:27:54
Billable: No

Grand total: 2:27:54
