### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#34]
- [x] O redirect do https tá bem ruim.. recarrega visivelmente. Fazer via node.
- [x] Pensar como iremos ter um front pra cada subdominio (tenho uma ideia)
- [x] Incluir title e metadescription dinâmico
- [ ] Incluir logo da cidade como imagem de compartilhamento
- [ ] Incluir favicon nosso

Será que vale a pena ter dados estruturados, dos pontos no mapa?

**Comment by jfbaraky** [comment]
via Hubstaff
User: João Fernando Baraky

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/16/21 - 04/20/21
Work session total: 5:03:52
Billable: No

Grand total: 5:03:52
