### ISSUE TITLE
Criar importador de places - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#35]
## Objetivo
A prefeitura tem uma lista de pontos de vacinação, e outras também certamente terão. Precisamos fazer um `command` que lê um arquivo e injeta os places no banco da prefeitura.M

- [Arquivo de places de Juiz de Fora](https://docs.google.com/spreadsheets/d/1VTzM1MTfU0aq6b7GjnEWc7oqO3pdeCBShbgNiqr8Nj0/edit?usp=sharing)
- Vamos discutir os nomes dos campos que a planilha precisa ter

## Tarefas
- [x] Criar command que recebe um arquivo xls/csv (só csv se for mais fácil), o id da prefeitura, e certifica os places
- [x] Para cada linha, conferir se já existe o place, se não existe criar, se existe atualizar

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/13/21 - 04/13/21
Work session total: 2:11:49
Billable: No

Grand total: 2:11:49
