### ISSUE TITLE
Adicionar Rollbar - 3h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#41]
## Objetivos
Incluir o Rollbar nos fronts pra gente capturar qualquer erro que aparecer.

## Tarefas
- [x] Adicionar Rollbar no Admin
- [x] Adicionar Rollbar no Portal
- [x] Adicionar Rollbar no Front
- [x] Caputar os erros nos lugares certos

**Comment by jfbaraky** [comment]
via Hubstaff
User: João Fernando Baraky

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/13/21 - 04/14/21
Work session total: 2:16:02
Billable: No

Grand total: 2:16:02
