### ISSUE TITLE
Bugfixes de homologação - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#47]
## Bugs 
- [x] `superAdmin` conseguir logar e usar o admin certinho
- [x] Quando `prefectureAdmin`, obter usuários apenas da prefeitura do cara (mas ninguem)
- [x] Quando `placeAdmin`, obter usuários apenas do place do cara (mas ninguem)
- [x] Admin não tá buildando por causa do style no lugar errado. Ajustar. Testar dar build local.
- [x] Dar update no place, sempre, usando a prefeitura na url

## Ajustes
- [x] Apagar dados do localStorage no logout
- [x] Tirar botão "atualizar fila" de ponto fechado
- [x] Ordenar places por ordem alfabetica
- [x] Exibir um loading enquanto não tem os usuários na tela (enquanto espera chegar)
- [x] Exibir um loading enquanto não tem os places na tela (enquanto espera chegar)
- [x] Ao atualizar a fila, deixar loading só uma vez na interface, ao invés de em cada item
- [x] Trocar menu "Atualizar" por "Pontos de Vacinação"

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/13/21 - 04/13/21
Work session total: 0:16:09
Billable: No

Grand total: 0:16:09

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/13/21 - 04/13/21
Work session total: 0:10:08
Billable: No

Grand total: 0:26:17
