### ISSUE TITLE
Autenticação em PT - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#48]
- [x] Ver pacote da autenticação do firebase, que está em inglês
- [x] Ver se solução é realmente clonar repo e fazer um PT
- [x] Passar para PT
- [ ] Conferir questão do crash do captcha (talvez abrir uma issue lá no repo)

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/14/21 - 04/14/21
Work session total: 0:24:43
Billable: No

Grand total: 0:24:43
