### ISSUE TITLE
Adicionar Rollbar no backend - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#51]
- [x] Adicionar Rollbar ao projeto
- [x] Ver como capturar todos os erros no Adonis v5, para serem sempre logados
- Vamos discutir como o Adonis captura as falhas, para vermos a necessidade de incluir try catch em todas as rotas

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/14/21 - 04/14/21
Work session total: 0:42:18
Billable: No

Grand total: 0:42:18
