### ISSUE TITLE
OnShanpshot e middleware com role - 4h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#52]
## Objetivo
O objetivo é manter a API sempre "escutando" as modificações, para ter dados sempre atualizados.

## Tarefas
- [x] Lidar com onSnapshot na API. Confirmar que mudanças em qualquer nível serão recebidas, para que os objetos que são retornados pelos endpoints estejam todos locais sempre, para evitar consumo.
- [x] Validar comigo a necessidade de usar um cache de memória
- [x] Middleware entender o `user` e o `admin`, entender as roles, entender se o usuário está ativo (ou se ainda não foi ativado, no caso da confirmação)
- [x] Confirmar que nenhum dado pode ser incluído/alterado/excluido no firestore por usuários não Autorizados. É preciso ter `user` ou `admin`, é preciso estar ativo.

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/14/21 - 04/14/21
Work session total: 3:46:13
Billable: No

Grand total: 3:46:13
