### ISSUE TITLE
Enviar email - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#54]
## Objetivo
Permitir a API enviar email para o endereço de email configurado no .env. Não precisa de template nem nada elaborado, é só enviar mesmo do jeito mais simples de implementar.

## Tarefas
- [x] Criar valor no .env com email principal
- [ ] Criar rota `/contact`, validar atributos (ver com quem estiver fazendo o form de nova prefeitura)
- [x] Enviar email e retornar 200

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/14/21 - 04/16/21
Work session total: 2:37:13
Billable: No

Grand total: 2:37:13
