### ISSUE TITLE
Coordenadas dos places - 3h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#55]
## Objetivo
O objetivo é salvar as coordenadas de cada place, para poder calcular a distância para o usuário.

## Tarefas
- [ ] Criar provider para consumir API do Google
- [ ] Incluir valores no .env
- [ ] Obter a coordenadas de cada place, a partir do ZIP
- [ ] Adicionar atributos no place de coordenada

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/15/21 - 04/15/21
Work session total: 0:06:40
Billable: No

Grand total: 0:06:40
