### ISSUE TITLE
Ajustes de front de homologação - 6h 

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#56]
## Front
- [x] Não exibir `internalTitle`
- [x] Não está mostrando o status dos places (adequar status pra inglês)
- [x] "Atualizado em", se não tiver valor não exibir
- [x] "Atualizado em", se lugar estiver fechado, não mostrar
- [x] Locais fechados, deixar cinza, no final, e com status "Fechado agora"
- [x] Quando clicar em "Buscar" dar alert "Ainda não implementado nesta versão"
- [x] Ajustar tamanho do texto "filas intensas"
- [x] Exibir data e hora moment, tipo "Ontem as 16:30", "As 14:33"
- [x] Trocar logo "Filômetro" por "Mapa da Vacina", só cria uma imagem com estas palavras mesmo, depois terá uma logo certinha
- [x] Colocar cor no background geral, pra permitir leitura enquanto não chega a imagem de bk

## Admin
- [x] Invite de `queueObserver` deve enviar a prefeitura e place, sempre, em 100% dos casos. Se for `superAdmin` ou `prefectureAdmin` convidando, ele terá que escolher no select o place. Se for `placeAdmin` convidando, o place é o mesmo dele.
- [x] `placeAdmin` Admin do local, não pode ver usuários admin da prefeitura, só ver usuário que sejam do mesmo place
- [x] Trocar logo "Filômetro" por "Mapa da Vacina", só cria uma imagem com estas palavras mesmo, depois terá uma logo certinha
- [x] Itens da grid não serem links 

## Admin auth - Baraky
- [ ] Ao autenticar, vai pra `/auth`, depois vai pra `/logout` sem nunca chamar o validate da api. Corrigir.
- [x] Ter uma view só de erro de login, que não será a `/logout`
- [x] Erro de login 401, exibir mensagem que vem da API
- [x] Erro de login que não for 401, exibir "Erro ao autenticar. Entre em contato com o administrador" - logar no Rollbar
- [ ] Rota de logout, fazer logou (apagar dados e sair do firebase) e dar redirect pro login

## Portal
- [x] Trocar logo "Filômetro" por "Mapa da Vacina" (pegar com Alessandro)
- [x] Colocar cor no background geral, pra permitir leitura enquanto não chega a imagem de bk (usar a mesma do front)

## Ajustar
- [x] Colocar loading do front, enquanto os dados não chegam
- [x] Obter dados da API novamente a cada minuto, não precisa exibir loading enquanto atualiza

**Comment by jfbaraky** [comment]
via Hubstaff
User: João Fernando Baraky

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/14/21 - 04/14/21
Work session total: 2:16:04
Billable: No

Grand total: 6:49:59

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/14/21 - 04/15/21
Work session total: 4:33:55
Billable: No

Grand total: 6:49:59
