### ISSUE TITLE
Ajustes de frontend - homologação com prefeitura - 3h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#66]
## Admin
- [x] Exibir primeiro nome e role do usuário na App Bar
- [x] Apresentar um loading depois de autenticar, antes do dashboard. As vezes demora um tempo ali.. dai tendo um loading o usuário sabe que está carregando. Conferir o que ele faz neste tempo exatamente, se puder.
- [x] No admin apenas, onde o cara informa o tamanho da fila exibir como abaixo. Se quiser pode dividir em duas linhas pra "caber melhor" no mobile se precisar. Mandar um print pra gente dar um ok.
```
Sem fila - menos de 5 minutos de espera
Pouca fila - até 10 minutos de espera
Filas moderadas - até 20 minutos de espera
Filas intensas - além de 20 minutos de espera
```

## Front
- [x] Pra Juiz de Fora, atualizar logos, hardcoded mesmo por enquanto. Com a logo da prefeitura (escolha uma das duas) e da campanha de imunização junto. Mandar um print pra gente dar ok final.
[Logos.zip](https://github.com/app-masters/mapa-da-vacina/files/6313460/Logos.zip)

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/15/21 - 04/15/21
Work session total: 2:57:19
Billable: No

Grand total: 2:57:19
