### ISSUE TITLE
Abrir e fechar automáticamente os pontos - 4h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#67]
## Tarefas
- [x] Ter horários no place de abertura e fechamento, atributo se abre hoje, se abre amanha
- Ler a collection local para os dois casos abaixo
- [x] Atualizar o abre hoje - criar cronJob que rode depois da meia noite, e irá pegar o valor do amanha e colocar no hoje - deixar um rollbar info só pra gente saber que aconteceu
- [x] Abrir e fechar automaticamente os pontos - criar cronJob do node, que roda a cada minuto, obter os places que deveriam abrir (ou fechar) no último 1 minuto - abrir (ou fechar) - deixar um rollbar info quando abrir ou fechar algum lugar automaticamente - incluir registro em `queueUpdate`
- [x] Atualizar ordem do enpoint, de forma que os "não abre hoje" fiquem por último, depois dos fechados
- [x] Conferir query do endpoint de prefeitura, para obter só places `active=true`
- [x] Conferir query da function que conta os places, para obter só places `active=true`

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/15/21 - 04/15/21
Work session total: 3:20:26
Billable: No

Grand total: 3:20:26
