### ISSUE TITLE
CRUD de pontos de vacinação - 5h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#68]
## Objetivo
O objetivo é permitir a prefeitura gerir os pontos de vacinação.

- Antes de começar, vamos discutir para alinhar as ideias.
- 
## Permissões
- [x] `superAdmin` irá ver todas as prefeituras, e dentro delas todos os pontos (igual ao da atualização)
- [x] `prefectureAdmin` verá só a prefeitura dele com todos os pontos (em qualquer situação)
- [x] `placeAdmin` verá só a prefeitura dele com o ponto dele

## Listagem
- [x] Obter do firestore já com os filtros de acordo com a permissão (pra economizar recursos lá)
- [x] Listar por ordem de `title`, com as colunas "Ponto" `title`, "Tipo" `type`,  "Abre hoje" `openToday`, "Abre amanhã" `openTomorrow`, "Horário" , "Ativo" `active`
- [x] Na grid, pro horário exibir `{openAt} às {closeAt}`, pro ativo exibir um ícone de check apenas para os ativos, para os dois "abre" exibir o ícone do check quando true
- [x] Botão para incluir novo place
- [x] Botão na grid para editar place

###  Campos do CRUD:
```
title (Ao sair dele, se internalTitle estiver null, copiar o valor)
type - (select ou radio com tipos)
active (check, deixar true por padrão)
addressDistrict (bairro)
addressStreet (deixar exemplo "Av Barão do Rio Branco 3480")
addressZip (exibir com máscara, salvar sem máscara)
addressCityState (Já pode iniciar com a cidade e estado da prefeitura, no formato "cidade - estado")
googleMapsUrl (link para Google Maps)
internalTitle (Título interno)

```
### Campos com valor automático:
```
open = false
prefectureId = obter do parent
queueStatus = closed
```

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/15/21 - 04/15/21
Work session total: 3:04:02
Billable: No

Grand total: 3:04:02
