### ISSUE TITLE
Criar design do portal - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#7]
## Objetivo
O objetivo é criar a interface do portal, onde as pessoas irão acessar, mas de forma bem simples e objetiva. Pode ser bem parecido mesmo com o de salvador. Em outra issue será a implementação.

- Se inspirar em [filometro.saude.salvador.ba.gov.br](https://filometro.saude.salvador.ba.gov.br/)
- Enviar prints no canal pra gente validar

## Cabeçalho
- [x] Logomarca
- [x] Logo da prefeitura

## Resumo
Uma section com alguns dados e ações rápidas
- Pontos de vacinação na cidade / X
- Pontos de vacinação abertos agora / Y
- Filas de pontos fixo / Sem filas, Poucas filas, Filas moderadas, Filas intensas
- Forma da pessoa informar a idade e cep para saber onde vacinar (inputs e botão)

## Pontos de vacinação
- Eu não colocaria título em nada, só os valoes
- [x] Dois grupos: Pontos fixos (que são os postos de saúde), Drive Thru
- [x] Lista os locais apenas com: titulo do local, endereço, situação, última atualização (pra este eu colocaria titulo), grupos especiais

## Rodapé
- [x] Incluir [nossa logo] "Desenvolvido por App Masters" com link pro nosso site
- [x] Incluir [logo github] "Projeto open source" com link pro repositório
- [x] Incluir link "Criar filometro pra minha prefeitura" que levará para uma outra view depois

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/07/21 - 04/07/21
Work session total: 2:05:13
Billable: No

Grand total: 2:05:13
