### ISSUE TITLE
Ajustes de back e frontend - homologação com prefeitura - 4h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#74]
- Cada prefeitura pode decidir se mostrará ou não o "Atualizado há"
- O novo estado "aberto"

## Backend
- [x] Incluir atributo "showQueueUpdatedAt" bool
- [x] No endpoint da prefeitura, antes de salvar no cache, se `queueUpdatedAt` tem mais de 30 minutos, retornar pro front `queueStatus=open` ao invés do estado que realmente está
- [x] Ao abrir o local (noCron), setar o estado `open` ao invés de `noQueue`

### Admin
- No admin, podemos mostrar o tempo da ultima atualização, sem problema
- [x] Ao abrir um local, setar `queueStatus=open` 
- [x] Ao informar o status da fila, enviar um atributo novo `user` com o "id" do usuário autenticado (só pra ficar registrado quem atualizou)
- [x] Não permitir no admin, selecionar o estado `open` no popup da fila
### Front
- [x] Comentar a section "Encontre seu ponto" por agora
- [x] Se `prefecture.showQueueUpdatedAt===false`, não mostrar o "Atualizado há" 
- [x] Preparar para exibir novo estado "aberto" (`queueStatus=open`) que pode usar a cor do "sem fila atual", e o texto será só "Aberto"
- [x] Colocar o status "sem fila" mais pra verde talvez

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/16/21 - 04/16/21
Work session total: 0:03:05
Billable: No

Grand total: 0:25:46

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/15/21 - 04/15/21
Work session total: 0:22:41
Billable: No

Grand total: 0:25:46
