### ISSUE TITLE
Criar CI de deploy para Firebase - 2h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#77]
- [x] Deploy das keys
- [x] Deploy das functions
- [x] Deploy das rules
- [x] logar no rollbar com info quando enviar SMS, envio e resultado

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/16/21 - 04/16/21
Work session total: 2:59:10
Billable: No

Grand total: 2:59:10
