### ISSUE TITLE
Importar CSV - 5h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#78]
## Objetivos
O objetivo aqui é permitir enviarmos um CSV com os pontos de vacinação pelo admin, para facilitar a gestão das cidades.

## Tarefas Backend
- [x] Sanitizar campos de textos (todos) antes de criar o slug, e antes de salvar. Lembrar de dar TRIM nos campos. Remover quebras de linhas nos campos. Ajustar maiusculas e minusculas. Inicio com "UBS " e "AMA/UBS " ser sempre maiuscula.
- [x] `internalTitle` se não vier na planilha, usar slug do `title`
- [x] Se vier sem `type`, marcar como fixo
- [x] Considerar `open` e `queueStatus=open` quando estiver no horário ativo (só na importação aqui, não fazer via `queueStatus`,  setar direto no `place`)
- [x] Abrir PR para command já funcionar assim
- [x] Endpoint que irá receber o CSV
- [x] Apenas usuário `superAdmin` e `prefectureAdmin` podem enviar
- [x] `prefectureAdmin` só atualiza da prefeitura dele
- [x] Opção de "desativar" as que não estiverem na lista, assim, as que não forem enviadas, serão desativadas. Se estiver true, desativar todos os places (da cidade) antes de iniciar a importação
- [x] Ler CSV e atualizar os places

## Tarefas Frontend
Só nós enviaremos isso hoje
- [x] Apenas usuário `superAdmin` e `prefectureAdmin` terá um botão "Importar CSV" dentro da lista de cada prefeitura
- [x] Ao clicar, abrir popup pra enviar o arquivo para aquela prefeitura - exibir no popup o nome da cidade, pra confirmar que está no registro certo
- [x] Input check "Desativar pontos que não estiverem na lista"
- [x] Enviar post pra API, com a `prefectureId` na requisição
- [x] Se tiver sucesso, mostrar, se falhar, avisar também

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/16/21 - 04/16/21
Work session total: 2:10:22
Billable: No

Grand total: 5:11:15

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/16/21 - 04/16/21
Work session total: 3:00:53
Billable: No

Grand total: 5:11:15
