### ISSUE TITLE
Modelo do banco e schemas - 4h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#8]
- [ ] Declarar os tipos como do documento a seguir.  
![__Filômetro___DbDesigner_net](https://user-images.githubusercontent.com/2242549/113879730-33cc2100-9791-11eb-865b-d4b71e3f6bc5.png)

- [ ] Calcular o quanto 1mb (limite do documento) aguentaria de informações

- [ ] Pesquisar melhor forma de obter as coleções no inicio e ativar listeners para escutar atualizações

- [ ] Repostório?

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Filômetro - https://app.hubstaff.com/projects/1458472
Date Range: 04/07/21 - 04/08/21
Work session total: 3:42:24
Billable: No

Grand total: 3:42:24
