### ISSUE TITLE
Demonstração / sampleMode - 3h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#80]
## Objetivo
O objetivo é exibir uns textos em algumas situações "novas"
- Se incluirmos uma cidade na mão, sem a prefeitura da cidade "autorizar", teremos um atributo indicando isso na `prefecture`, 

## Tarefas backend
- [x] Criar cronJob que rode a cada 5 minutos, que irá atualizar o status de algumas filas da cidade demostranção
- [x] Obter cidade com "Demonstração" no título
- [x] Obter 25% dos places `open` aleatóriamente
- [x] Mudar o status da fila inserindo um `queueUpdate`

## Tarefas frontend
- [x] Quando `prefecture.sampleMode===true` abaixo da lista de places, incluir um box bem chamativo, amarelo ou vermelho, com os dizeres "Estamos aguardando o contato da prefeitura de {city} para apresentarmos também o tamanho da fila em cada ponto de vacinação.<br>Se você é da prefeitura de {city} entre em <a>contato</a> conosco" - link do contato `https://api.whatsapp.com/send?phone=5532988735683&text=Sou da prefeitura de {city} e gostaria de saber como utilizar o Mapa da Vacina.`
- [x] Quando houver o termo "Demonstração" existir no título da cidade, incluir um box verde acima dos pontos, com os dizeres "Esta é uma cidade de demonstração do sistema Mapa da Vacina, para que você possa entender como os pontos de vacinação são apresentados com suas respectivas filas."

## Logo
- [x] Incluir atributos `primaryLogo` e `secondaryLogo` em `prefecture`
- [x] Se vier `primaryLogo`, exibir, se não vier exibir um texto "Prefeitura de {city}"
- [x] Abrir PR e avisar

## Outros
- [x] Adicionar link "Ver todas as cidades" que leva para `https://www.mapadavacina.com.br`
- [x] Ajustar logo da App Masters que está desproporcional   
![Logos_adaptadas_and_https___saopaulo_mapadavacina_com_br](https://user-images.githubusercontent.com/2242549/115071930-45b66e00-9ecd-11eb-8ec4-8b29975d65a5.png)
- [x] Lidar com valores que virão vazios ai   
![https___saopaulo_mapadavacina_com_br](https://user-images.githubusercontent.com/2242549/115073201-5f0bea00-9ece-11eb-8b15-041adb9a6055.png)

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/16/21 - 04/16/21
Work session total: 1:14:37
Billable: No

Grand total: 3:13:36

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/16/21 - 04/16/21
Work session total: 1:58:59
Billable: No

Grand total: 3:13:36
