### ISSUE TITLE
Ajustes de publicação - 16h

### ISSUE THREAD

**Issue by TiagoGouvea** [app-masters/mapa-da-vacina#91]
- Não fechar essa issue

## Portal
- [x] Tirar todos os preços, deixar só "Sob consulta"
- [x] Na coluna "Pago" trocar por "Assinantes", "Gratis" vira "Gratuito"
- [x] Incluir "Solicitar novos recursos" nos planos
- [x] Incluir este header no HTML do portal e do front (Google AdSense)
<script data-ad-client="ca-pub-4701885567513809" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
- [x] Incluir um "Fale conosco" no menu, que abre meu whatsapp direto, com o text "Gostaria de falar a respeito do Mapa da Vacina".
- [x] Trocar "Caso optem pela ..." por "Os valores de assinatura variam de acordo com a quantidade de habitantes em sua cidade. Crie o Mapa da Vacina de sua prefeitura para lhes informamos a respeito de valores."
- [x] Incluir uma página "Como funciona" que levará para a landing page

## Front
- [x] Os minutos, pra destacar "atualizado" em vermelho na lista, ser uma ENV (me informar a ENV)
- [x] Na obtenção de dados novos (interval), se falhar, não sumir com os dados que já tinham na tela, deixar os dados que já tinha lá.
- [x] Se place aberto, exibir "Fecha às X"
- [x] Se place fechado, mas `openTomorrow` exibir "Abre amanhã as X"
- [x] Se place fechado, não `openTomorrow===false` exibir "Não abrirá amanhã"
- [x] Se tiver (parenteses) no titulo do place ([exemplo](http://brasilia.mapadavacina.com.br/))av, jogar ele pra um `small` e remover os parentesis
- [x] Se tiver google maps, botão "como chegar" ou pin (envie um print por favor)
- [x] Incluir Analytics (front e portal)
- [x] Na hora que abre o front, aparece “Prefeitura de undefined”, dai quando chega o dado muda. Deixar sem texto talvez enquanto carrega.
- [x] Ajustar para a largura desta parada pra ficar igual em todos   
![Mapa_da_Vacina___Encontre_a_vacina_para_COVID](https://user-images.githubusercontent.com/2242549/115113931-223e0280-9f63-11eb-927c-81b633fbd7bb.png)
- [x] Ultima atualização, não mostrar quando um atributo lá estiver true. Me confirme.
- [x] Se `(prefecture.showQueueUpdatedAt && prefecture.showQueueUpdatedAt===false) || queueStatus===open || queueStatus===close || open===false`, não mostrar o "Atualizado há"
- [x] Se não tiver a logo da cidade, exibir `<h1>Pontos de Vacinação em {city}</h1>`, distribuir melhor o espaço (pegar as duas colunas), fonte maior e tal.
- [x] Cor do `noQueue`  ser `#16A05A` (portal e admin)
- [x] Os quadrados de quantidade, deixar em duas colunas no desktop
- [x] Lá no final, onde tem o box vermelho, duplicar o código só que com a seguinte regra nova: se não tiver logo e se todos os pontos estiverem `queueStatus==open || close`, exibir o box vermelho com os dizeres: "Assim que a prefeitura de <strong>{city}</strong> entrar em contato conosco, será apresentado também: - O tamanho da fila em cada ponto de vacinação; - Datas de vacinação por idade; - Os pontos de vacinação mais próximos para vacinar; - Os melhores horários para em cada ponto; Se você é da pre....." (os - são `<li>`) Esta regra fará aparecer o box em São Paulo hoje, mas não em Brasilia.

## Backend
- [x] Normalizar (maiusculas e minusculas) os endereços, tá tudo maiusculo em SP
- [x] Os minutos, pra mostrar como "aberto" ser uma ENV (me informar a ENV)
- [x] Na rota `prefecture-list` não precisa retornar os places

## Admin
- [x] Quando inclui um place, ele estava (pelo visto) open, mas com `queueStatus=closed`. Todos que eu inclui ficaram assim. Pelo admin tive que mandar abrir, pra ele acertar o status. Validar com o Bruno a melhor forma de fazer isso.
![https___admin_mapadavacina_com_br_place_update](https://user-images.githubusercontent.com/2242549/115220957-8e457580-a0df-11eb-8b8e-ff40bf9cc321.png)
- [x] Parece que é preciso sempre desmarcar e marcar novamente o check de ativo, para ele deixar salvar
- [x] Form de place - colocar os 3 checks na mesma linha, incluir mais um "Aberto agora", que é o `open`, pra faciltiar
- [x] Form de place - Horário, trazer sempre o último salvo (guardar no local storage quando salvar, pra usar no próximo)
- [x] Na view de atualização dos pontos, forçar um render a cada minuto, não precisa obter dado nenhum, só renderizar a view novamente (pra atualizar os tempo "Atualizado X minutos atrás..")
- [x] Na lista de pontos (atualizar), pra quem vê mais de um ponto, ter um botão pra filtrar os places [Todos|Abertos]. Filtrar no render, não na obtenção.
- [x] Os minutos, pra destacar em vermelho na lista que o lugar foi atualizado muito tempo atrás, ser uma ENV (me informar a ENV)
- [x] Não confirmar para abrir place, deixar um loading no botão mesmo. Pra fechar, manter confirmação.
- [x] Deixar botões da fila maiores (largura), tipo uns 75% da largura
- [x] Bugs não resolvido: exibir loading enquanto baixa o bundle, em `auth` baixando `dashboard` - deixar um estado de loading em auth (validar com Baraky)
- [x] Ajustar título das roles no select de invite, pra ficar mais claro "Administrador na prefeitura", "Administrador no ponto de vacinação", "Observador da fila"
- [x] "Taxas de mensagens e dados podem ser aplicáveis." remover
- [x] Incluir rodapé com "Desenvolvido pela App Masters" ao centro, só texto, link pro nosso site, sem logo.
- [x] Incluir CEP no form de place
- [x] Não exigir CEP nem bairro
- [x] Incluir inputs para informar "Abre hoje" e "Abre amanhã" ao editar o place   
![https___admin_mapadavacina_com_br_place_list](https://user-images.githubusercontent.com/2242549/115080410-10b01880-9ed9-11eb-93c4-f03287db5864.png)

**Comment by jfbaraky** [comment]
via Hubstaff
User: João Fernando Baraky

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/16/21 - 04/22/21
Work session total: 8:17:11
Billable: No

Grand total: 21:31:47

**Comment by macanhajc** [comment]
via Hubstaff
User: Alessandro Macanha

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/16/21 - 04/22/21
Work session total: 5:47:38
Billable: No

Grand total: 21:31:47

**Comment by bmarcosps** [comment]
via Hubstaff
User: Bruno Marcos Pinheiro da Silva

Project: Mapa da Vacina - https://app.hubstaff.com/projects/1458472
Date Range: 04/16/21 - 04/20/21
Work session total: 7:26:58
Billable: No

Grand total: 21:31:47
